spring:
  datasource:
    url: ${DB_HOST:jdbc:mysql://192.168.0.11/assembly}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}  rabbitmq:    host: ${RABBIT_HOST:192.168.0.11}    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORLD:guest}

rabbit:
  results_dx: ${RESULTS_DX:results_dx}
  results_q: ${RESULTS_Q:results_q}
  routing_key: ${ROUTING_KEY:routing_key}
  
resttemplate:
  cpfurl: ${RESTTEMPLATE_CPFURL:https://user-info.herokuapp.com/users/{cpf}}  